Submission Form Raw Footage Requirement
stadust/pointercrate pull request #64
Opened 2022-07-24 18:41 UTC by NimbusGD

Edit the submission form to reflect the new raw footage requirement, along with the error message for missing it

2022-07-24 20:01 UTC, stadust requested changes
This switch clause needs to be updated 

https://github.com/stadust/pointercrate/blob/feefa6d3f53c0b189bc03bdb9da4f3ebe8991696/pointercrate-demonlist/src/error.rs#L234

~~I am actually slightly concered about rustc not raising an error here :thinking: ~~ nvm its because all the enum variants are locally `use`d, the invalid name just gets used as a variable. That's... unintiutive lol

Also, this input should be marked as required now (see the other inputs in the same file). Sorry, forgot about that when I told you how to implement this change :(

https://github.com/stadust/pointercrate/blob/feefa6d3f53c0b189bc03bdb9da4f3ebe8991696/pointercrate-demonlist-pages/src/components/submitter.rs#L93

2022-07-24 23:54 UTC, NimbusGD commented
I have pushed both requested changes to this pull request - hopefully it's all set now!

2022-07-25 07:22 UTC, stadust approved these changes

2022-07-25 07:22 UTC, stadust commented
Looks good now!

2022-07-25 07:23 UTC, merged